-- Phase 1: enrollment_tokens — one-time tokens that bind an installer to a tenant + endpoint identity.

CREATE TABLE public.enrollment_tokens (
    token             text PRIMARY KEY,
    organization_id   uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    created_by        uuid NOT NULL REFERENCES auth.users(id),
    created_at        timestamptz NOT NULL DEFAULT now(),
    expires_at        timestamptz NOT NULL DEFAULT (now() + interval '7 days'),
    used_at           timestamptz,
    used_by_endpoint  uuid REFERENCES public.endpoints(id) ON DELETE SET NULL,
    hostname_hint     text,
    runtime_hint      text CHECK (runtime_hint IS NULL OR runtime_hint IN ('powershell', 'dotnet')),
    channel           text NOT NULL DEFAULT 'stable' CHECK (channel IN ('stable', 'beta', 'canary'))
);

CREATE INDEX idx_enrollment_tokens_org ON public.enrollment_tokens(organization_id);
CREATE INDEX idx_enrollment_tokens_unused
    ON public.enrollment_tokens(organization_id)
    WHERE used_at IS NULL;

ALTER TABLE public.enrollment_tokens ENABLE ROW LEVEL SECURITY;

-- Only members of the org may see their tokens; only admins may create.
CREATE POLICY enrollment_tokens_select ON public.enrollment_tokens
    FOR SELECT TO authenticated
    USING (public.is_member_of_org(auth.uid(), organization_id));

CREATE POLICY enrollment_tokens_insert ON public.enrollment_tokens
    FOR INSERT TO authenticated
    WITH CHECK (
        created_by = auth.uid()
        AND public.is_admin_of_org(auth.uid(), organization_id)
    );

-- Service role bypasses RLS for the agent-enroll edge function which validates tokens.
COMMENT ON TABLE public.enrollment_tokens IS
    'One-time tokens generated by org admins, exchanged by installer for permanent endpoint credentials. See agent-enroll edge function.';
